/* dsh-muse-ui client bundle — generated by build/build-ui.mjs; do not edit. */
window.__ModuleLoader__.load({
	id: "dsh-muse-ui",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// plugins/dsh-muse-ui/src/client.jsx
var client_exports = {};
__export(client_exports, {
  apply: () => apply,
  inject: () => inject
});
module.exports = __toCommonJS(client_exports);
var import_react = require("react");

// plugins/dsh-muse-ui/src/locales.js
var NS = "muse";
var zh = {
  "view.muse": "Muse \u5DE5\u4F5C\u53F0",
  /* 首屏（人话层） */
  "hero.status.none": "\u672A\u5F00\u59CB",
  "hero.status.draft": "\u5DF2\u7ACB\u9879",
  "hero.status.active": "\u8FDB\u884C\u4E2D",
  "hero.status.waiting_approval": "\u7B49\u5F85\u5BA1\u6279",
  "hero.status.blocked": "\u53D7\u963B",
  "hero.status.done": "\u5DF2\u5B8C\u6210",
  "hero.status.failed": "\u5DF2\u5931\u8D25",
  "hero.status.cancelled": "\u5DF2\u53D6\u6D88",
  "hero.progress": "{done}/{total} \u6B65 \xB7 {pct}%",
  "artifacts.empty": "\u4EFB\u52A1\u4EA4\u4ED8\u540E,\u8FD9\u91CC\u4F1A\u5217\u51FA\u4EA4\u4ED8\u7269\u6E05\u5355",
  "latest.prefix": "\u6700\u65B0",
  "tech.toggle": "\u6280\u672F\u7EC6\u8282(\u526F\u4F5C\u7528 \xB7 \u8BC1\u636E \xB7 \u8BC4\u6D4B \xB7 \u52A8\u6001)",
  "eval.title": "\u8BC4\u6D4B\u6307\u6807",
  "empty.title": "\u7B49\u5F85 Muse \u6D3B\u52A8",
  "empty.body": "\u672C\u4F1A\u8BDD\u8FD8\u6CA1\u6709\u4EFB\u52A1\u6863\u6848\u3002agent \u7528 workunit / effect / evidence \u7B49\u5DE5\u5177\u5F00\u59CB\u5E72\u6D3B\u540E,\u8FD9\u91CC\u4F1A\u5B9E\u65F6\u5C55\u793A\u5B83\u7684\u7ED3\u6784\u5316\u5DE5\u4F5C\u65B9\u5F0F:\u4EFB\u52A1\u65C5\u7A0B\u3001\u526F\u4F5C\u7528\u6D41\u6C34\u7EBF\u3001\u8BC1\u636E\u5899\u4E0E\u4EA4\u4ED8\u6838\u9A8C\u3002",
  "stats.museCalls": "Muse \u8C03\u7528",
  "stats.writeOps": "\u5199\u64CD\u4F5C",
  "stats.executed": "\u5DF2\u6267\u884C",
  "stats.denied": "\u62A4\u680F\u62E6\u622A",
  "stats.failed": "\u5931\u8D25",
  /* 任务旅程 */
  "journey.title": "\u4EFB\u52A1\u65C5\u7A0B",
  "journey.none": "\u672C\u4F1A\u8BDD\u5C1A\u65E0\u4EFB\u52A1\u6863\u6848",
  "milestone.draft": "\u7ACB\u9879",
  "milestone.active": "\u6267\u884C\u4E2D",
  "milestone.verify": "\u6838\u9A8C",
  "milestone.done": "\u5DF2\u4EA4\u4ED8",
  "journey.objective": "\u76EE\u6807",
  "journey.plan": "\u8BA1\u5212",
  "journey.constraints": "\u7EA6\u675F",
  "journey.alert.waiting_approval": "\u4EFB\u52A1\u7B49\u5F85\u5BA1\u6279\u4E2D\u2026",
  "journey.alert.blocked": "\u4EFB\u52A1\u53D7\u963B",
  "journey.failed": "\u4EFB\u52A1\u5931\u8D25",
  "journey.cancelled": "\u4EFB\u52A1\u5DF2\u53D6\u6D88",
  "journey.steps": "\u6B65\u9AA4",
  "journey.steps.empty": "\u6682\u65E0\u6B65\u9AA4",
  "journey.budget.tokens": "\u9884\u7B97",
  "journey.budget.failures": "\u5931\u8D25\u989D\u5EA6",
  "journey.budget.rounds": "\u8F6E\u6B21",
  /* 副作用流水线 */
  "pipeline.title": "\u526F\u4F5C\u7528\u6D41\u6C34\u7EBF",
  "pipeline.none": "\u6682\u65E0\u526F\u4F5C\u7528",
  "pipeline.station.proposed": "\u63D0\u8BAE",
  "pipeline.station.approved": "\u5165\u8D26",
  "pipeline.station.executed": "\u6267\u884C",
  "effect.status.proposed": "\u5DF2\u63D0\u8BAE",
  "effect.status.approved": "\u5DF2\u6279\u51C6",
  "effect.status.executing": "\u6267\u884C\u4E2D",
  "effect.status.executed": "\u5DF2\u6267\u884C",
  "effect.status.failed": "\u5931\u8D25",
  "effect.status.denied": "\u5DF2\u62E6\u622A",
  "effect.status.rolled_back": "\u5DF2\u56DE\u6EDA",
  "effect.action.fs.write": "\u5199\u5165",
  "effect.action.fs.edit": "\u7F16\u8F91",
  "effect.action.shell.exec": "\u547D\u4EE4",
  "effect.origin.auto": "\u62A4\u680F",
  "effect.origin.explicit": "\u767B\u8BB0",
  /* 证据墙 */
  "evidence.title": "\u8BC1\u636E\u5899",
  "evidence.none": "\u6682\u65E0\u8BC1\u636E",
  "trust.trusted": "\u53EF\u4FE1",
  "trust.untrusted": "\u5B58\u7591",
  "fresh.ok": "\u6709\u6548",
  "fresh.stale": "\u8FC7\u671F",
  /* 交付核验 */
  "delivery.title": "\u4EA4\u4ED8\u6838\u9A8C",
  "delivery.verified": "\u5DF2\u6838\u9A8C\u4EA4\u4ED8",
  "delivery.unverified": "\u5F85\u6838\u9A8C",
  "delivery.artifacts": "\u4EA4\u4ED8\u7269",
  "delivery.noEval": "\u5C1A\u65E0\u8BC4\u6D4B\u62A5\u544A",
  "delivery.eval.verified": "\u9A8C\u8BC1\u6210\u529F\u7387",
  "delivery.eval.duplicates": "\u91CD\u590D\u526F\u4F5C\u7528\u7387",
  "delivery.eval.tokens": "\u7D2F\u8BA1\u6210\u672C",
  /* 工具调用流 */
  "feed.title": "\u5B9E\u65F6\u52A8\u6001",
  "feed.empty": "\u6682\u65E0\u52A8\u6001",
  "feed.muse": "Muse",
  "feed.write": "\u5199\u64CD\u4F5C",
  "feed.status.running": "\u8FDB\u884C\u4E2D",
  "feed.status.ok": "\u5B8C\u6210",
  "feed.status.denied": "\u88AB\u62E6\u622A",
  "feed.status.error": "\u51FA\u9519"
};
var en = {
  "view.muse": "Muse Studio",
  "hero.status.none": "Not started",
  "hero.status.draft": "Planned",
  "hero.status.active": "Working",
  "hero.status.waiting_approval": "Awaiting approval",
  "hero.status.blocked": "Blocked",
  "hero.status.done": "Done",
  "hero.status.failed": "Failed",
  "hero.status.cancelled": "Cancelled",
  "hero.progress": "{done}/{total} steps \xB7 {pct}%",
  "artifacts.empty": "Deliverables will be listed here once the task completes",
  "latest.prefix": "Latest",
  "tech.toggle": "Technical details (effects \xB7 evidence \xB7 eval \xB7 activity)",
  "eval.title": "Evaluation",
  "empty.title": "Waiting for Muse activity",
  "empty.body": "No work unit yet. Once the agent starts working through workunit / effect / evidence tools, this view shows its structured workflow live: task journey, effect pipeline, evidence wall and delivery verification.",
  "stats.museCalls": "Muse calls",
  "stats.writeOps": "Write ops",
  "stats.executed": "Executed",
  "stats.denied": "Guardrail denials",
  "stats.failed": "Failed",
  "journey.title": "Task journey",
  "journey.none": "No work unit in this session",
  "milestone.draft": "Draft",
  "milestone.active": "Working",
  "milestone.verify": "Verify",
  "milestone.done": "Delivered",
  "journey.objective": "Objective",
  "journey.plan": "Plan",
  "journey.constraints": "Constraints",
  "journey.alert.waiting_approval": "Waiting for approval\u2026",
  "journey.alert.blocked": "Blocked",
  "journey.failed": "Task failed",
  "journey.cancelled": "Task cancelled",
  "journey.steps": "Steps",
  "journey.steps.empty": "No steps yet",
  "journey.budget.tokens": "Budget",
  "journey.budget.failures": "Failures",
  "journey.budget.rounds": "Rounds",
  "pipeline.title": "Effect pipeline",
  "pipeline.none": "No effects",
  "pipeline.station.proposed": "Propose",
  "pipeline.station.approved": "Ledger",
  "pipeline.station.executed": "Execute",
  "effect.status.proposed": "proposed",
  "effect.status.approved": "approved",
  "effect.status.executing": "running",
  "effect.status.executed": "executed",
  "effect.status.failed": "failed",
  "effect.status.denied": "denied",
  "effect.status.rolled_back": "rolled back",
  "effect.action.fs.write": "write",
  "effect.action.fs.edit": "edit",
  "effect.action.shell.exec": "cmd",
  "effect.origin.auto": "rail",
  "effect.origin.explicit": "ledger",
  "evidence.title": "Evidence wall",
  "evidence.none": "No evidence",
  "trust.trusted": "trusted",
  "trust.untrusted": "untrusted",
  "fresh.ok": "fresh",
  "fresh.stale": "stale",
  "delivery.title": "Delivery",
  "delivery.verified": "Verified delivery",
  "delivery.unverified": "Unverified",
  "delivery.artifacts": "Artifacts",
  "delivery.noEval": "No eval report yet",
  "delivery.eval.verified": "verified rate",
  "delivery.eval.duplicates": "dup effects",
  "delivery.eval.tokens": "total cost",
  "feed.title": "Live activity",
  "feed.empty": "Nothing yet",
  "feed.muse": "Muse",
  "feed.write": "write",
  "feed.status.running": "running",
  "feed.status.ok": "done",
  "feed.status.denied": "denied",
  "feed.status.error": "error"
};

// plugins/dsh-muse-ui/src/client.jsx
var import_jsx_runtime = require("react/jsx-runtime");
var inject = ["slots", "sessions", "locale"];
var STYLE_ID = "dsh-muse-ui/styles";
var CSS = `
.muse-view { display: flex; flex-direction: column; gap: 12px; height: 100%; min-height: 0; padding: 14px 16px; overflow-y: auto; box-sizing: border-box; font-size: 12.5px; color: var(--dsw-alias-label-primary, #e8e8e8); }
.muse-view * { box-sizing: border-box; }
@keyframes muse-pulse { 0%,100% { box-shadow: 0 0 0 0 color-mix(in srgb, currentColor 45%, transparent); } 50% { box-shadow: 0 0 0 5px transparent; } }
@keyframes muse-breathe { 0%,100% { opacity: .55; } 50% { opacity: 1; } }
/* ============ \u9996\u5C4F\uFF1AHero \u4EFB\u52A1\u5361 ============ */
.muse-hero { border: 1px solid var(--dsw-alias-border-l2, #303030); border-radius: 14px; background: var(--dsw-alias-bg-layer-1, #1d1d1d); padding: 16px 18px 14px; display: flex; flex-direction: column; gap: 10px; }
.muse-hero-top { display: flex; align-items: center; gap: 10px; }
.muse-status { display: inline-flex; align-items: center; gap: 6px; font-size: 12px; font-weight: 600; padding: 3px 12px 3px 8px; border-radius: 999px; flex: none; }
.muse-status .muse-status-dot { width: 8px; height: 8px; border-radius: 50%; background: currentColor; }
.muse-status.is-blue { color: var(--dsw-alias-state-business-primary, #4a7dff); background: color-mix(in srgb, var(--dsw-alias-state-business-primary, #4a7dff) 13%, transparent); }
.muse-status.is-blue .muse-status-dot { animation: muse-breathe 1.6s ease infinite; }
.muse-status.is-green { color: var(--dsw-alias-state-success-primary, #5cb85c); background: color-mix(in srgb, var(--dsw-alias-state-success-primary, #5cb85c) 13%, transparent); }
.muse-status.is-amber { color: var(--dsw-alias-state-warn-label, #d90); background: color-mix(in srgb, var(--dsw-alias-state-warn-label, #d90) 12%, transparent); }
.muse-status.is-amber .muse-status-dot { animation: muse-breathe 2.2s ease infinite; }
.muse-status.is-red { color: var(--dsw-alias-state-error-primary, #f66); background: color-mix(in srgb, var(--dsw-alias-state-error-primary, #f66) 12%, transparent); }
.muse-status.is-dim { color: var(--dsw-alias-label-tertiary, #999); background: var(--dsw-alias-bg-layer-2, #2a2a2a); }
.muse-hero-objective { margin: 0; font-size: 14.5px; font-weight: 600; line-height: 1.55; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; overflow: hidden; }
.muse-progress { display: flex; align-items: center; gap: 10px; }
.muse-progress-track { flex: 1; height: 8px; border-radius: 4px; background: var(--dsw-alias-bg-layer-2, #2c2c2c); overflow: hidden; }
.muse-progress-fill { height: 100%; border-radius: 4px; background: var(--dsw-alias-state-business-primary, #4a7dff); transition: width .5s ease; min-width: 0; }
.muse-progress.is-done .muse-progress-fill { background: var(--dsw-alias-state-success-primary, #5cb85c); }
.muse-progress.is-warn .muse-progress-fill { background: var(--dsw-alias-state-warn-label, #d90); }
.muse-progress.is-fail .muse-progress-fill { background: var(--dsw-alias-state-error-primary, #f66); }
.muse-progress-label { flex: none; font-size: 12px; font-weight: 600; font-variant-numeric: tabular-nums; color: var(--dsw-alias-label-secondary, #bbb); }
/* \u6B65\u9AA4\u6E05\u5355\uFF08\u7EB5\u5411\u3001\u5168\u6807\u9898\u3001\u4E00\u773C\u53EF\u8BFB\uFF09 */
.muse-steplist { display: flex; flex-direction: column; gap: 2px; margin-top: 2px; }
.muse-steprow { display: flex; align-items: center; gap: 10px; padding: 6px 10px; border-radius: 9px; line-height: 1.45; }
.muse-steprow .muse-stepicon { flex: none; width: 20px; height: 20px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 11px; font-style: normal; background: var(--dsw-alias-bg-layer-2, #2c2c2c); color: var(--dsw-alias-label-dimmed, #666); }
.muse-steprow .muse-steptitle { min-width: 0; overflow-wrap: anywhere; color: var(--dsw-alias-label-tertiary, #999); }
.muse-steprow.is-done .muse-stepicon { background: color-mix(in srgb, var(--dsw-alias-state-success-primary, #5cb85c) 20%, var(--dsw-alias-bg-layer-2, #222)); color: var(--dsw-alias-state-success-primary, #5cb85c); }
.muse-steprow.is-done .muse-steptitle { color: var(--dsw-alias-label-secondary, #bbb); }
.muse-steprow.is-in_progress { background: color-mix(in srgb, var(--dsw-alias-state-business-primary, #4a7dff) 8%, transparent); }
.muse-steprow.is-in_progress .muse-stepicon { background: color-mix(in srgb, var(--dsw-alias-state-business-primary, #4a7dff) 28%, var(--dsw-alias-bg-layer-2, #222)); color: var(--dsw-alias-state-business-primary, #4a7dff); animation: muse-pulse 1.8s ease infinite; }
.muse-steprow.is-in_progress .muse-steptitle { color: var(--dsw-alias-label-primary, #eee); font-weight: 600; }
.muse-steprow.is-failed .muse-stepicon { background: color-mix(in srgb, var(--dsw-alias-state-error-primary, #f66) 22%, var(--dsw-alias-bg-layer-2, #222)); color: var(--dsw-alias-state-error-primary, #f66); }
.muse-steprow.is-failed .muse-steptitle { color: var(--dsw-alias-state-error-primary, #f66); }
.muse-steprow.is-skipped .muse-stepicon { opacity: .45; }
.muse-steprow.is-skipped .muse-steptitle { opacity: .55; text-decoration: line-through; }
/* \u8B66\u544A\u6761 */
.muse-alert { display: flex; align-items: center; gap: 8px; padding: 6px 12px; border-radius: 8px; font-weight: 600; animation: muse-breathe 2.2s ease infinite; }
.muse-alert.is-warn { color: var(--dsw-alias-state-warn-label, #d90); background: color-mix(in srgb, var(--dsw-alias-state-warn-label, #d90) 12%, transparent); }
.muse-alert.is-fail { color: var(--dsw-alias-state-error-primary, #f66); background: color-mix(in srgb, var(--dsw-alias-state-error-primary, #f66) 12%, transparent); animation: none; }
/* ============ \u9996\u5C4F\uFF1A\u4EA4\u4ED8\u7269\u5361 ============ */
.muse-card { border: 1px solid var(--dsw-alias-border-l2, #303030); border-radius: 12px; background: var(--dsw-alias-bg-layer-1, #1d1d1d); padding: 12px 14px; }
.muse-card h4 { margin: 0 0 10px; font-size: 11px; font-weight: 600; letter-spacing: .05em; text-transform: uppercase; color: var(--dsw-alias-label-caption, #8a8a8a); display: flex; align-items: center; gap: 7px; }
.muse-card h4 .muse-count { margin-left: auto; font-weight: 400; text-transform: none; letter-spacing: 0; color: var(--dsw-alias-label-dimmed, #777); }
.muse-deliver-head { display: flex; align-items: center; gap: 10px; margin-bottom: 10px; }
.muse-deliver-head h4 { margin: 0; flex: 1; }
.muse-seal { display: inline-flex; align-items: center; gap: 6px; font-size: 11px; font-weight: 600; padding: 3px 10px; border-radius: 999px; flex: none; }
.muse-seal.is-ok { color: var(--dsw-alias-state-success-primary, #5cb85c); background: color-mix(in srgb, var(--dsw-alias-state-success-primary, #5cb85c) 13%, transparent); }
.muse-seal.is-wait { color: var(--dsw-alias-state-warn-label, #d90); background: color-mix(in srgb, var(--dsw-alias-state-warn-label, #d90) 11%, transparent); }
.muse-artifacts { display: flex; flex-wrap: wrap; gap: 6px; }
.muse-artifact { display: flex; gap: 6px; align-items: center; padding: 4px 10px; border-radius: 8px; background: var(--dsw-alias-bg-layer-2, #232323); font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 11px; }
.muse-artifact .muse-art-check { color: var(--dsw-alias-state-success-primary, #5cb85c); font-weight: 700; }
.muse-artifact .muse-art-pending { color: var(--dsw-alias-label-dimmed, #888); }
/* ============ \u9996\u5C4F\uFF1A\u6700\u65B0\u52A8\u6001\u4E00\u884C ============ */
.muse-latest { display: flex; align-items: center; gap: 9px; padding: 9px 14px; border-radius: 12px; border: 1px solid var(--dsw-alias-border-l2, #303030); background: var(--dsw-alias-bg-layer-1, #1d1d1d); font-size: 12px; }
.muse-latest .muse-latest-ico { flex: none; width: 22px; height: 22px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 10.5px; background: color-mix(in srgb, var(--dsw-alias-state-business-primary, #4a7dff) 17%, transparent); }
.muse-latest.is-write .muse-latest-ico { background: color-mix(in srgb, var(--dsw-alias-state-warn-label, #d90) 17%, transparent); }
.muse-latest .muse-latest-label { min-width: 0; flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; color: var(--dsw-alias-label-secondary, #bbb); }
.muse-latest.is-denied .muse-latest-label { color: var(--dsw-alias-state-error-primary, #f66); }
.muse-latest .muse-latest-k { flex: none; color: var(--dsw-alias-label-dimmed, #888); font-size: 11px; }
/* ============ \u6280\u672F\u7EC6\u8282\uFF08\u70B9\u51FB\u5C55\u5F00\uFF09 ============ */
details.muse-tech { border: 1px solid var(--dsw-alias-border-l2, #303030); border-radius: 12px; background: var(--dsw-alias-bg-layer-1, #1d1d1d); }
details.muse-tech > summary { cursor: pointer; list-style: none; padding: 11px 14px; font-size: 12px; font-weight: 600; color: var(--dsw-alias-label-caption, #8a8a8a); display: flex; align-items: center; gap: 8px; border-radius: 12px; user-select: none; }
details.muse-tech > summary::-webkit-details-marker { display: none; }
details.muse-tech > summary::before { content: "\u25B8"; display: inline-block; transition: transform .18s ease; color: var(--dsw-alias-label-dimmed, #777); }
details.muse-tech[open] > summary::before { transform: rotate(90deg); }
details.muse-tech > summary:hover { color: var(--dsw-alias-label-primary, #eee); }
details.muse-tech .muse-tech-body { display: flex; flex-direction: column; gap: 12px; padding: 2px 14px 14px; }
details.muse-tech .muse-card { background: var(--dsw-alias-bg-layer-2, #232323); }
/* \u7EDF\u8BA1\u80F6\u56CA */
.muse-pills { display: flex; flex-wrap: wrap; gap: 8px; }
.muse-pill { display: flex; align-items: center; gap: 7px; padding: 5px 12px 5px 6px; border-radius: 999px; background: var(--dsw-alias-bg-layer-1, #1d1d1d); border: 1px solid var(--dsw-alias-border-l2, #303030); }
.muse-pill .muse-ico { width: 22px; height: 22px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 11px; background: color-mix(in srgb, currentColor 16%, transparent); }
.muse-pill b { font-size: 13px; font-weight: 650; font-variant-numeric: tabular-nums; }
.muse-pill span { color: var(--dsw-alias-label-tertiary, #8f8f8f); }
.muse-pill.is-blue { color: var(--dsw-alias-state-business-primary, #4a7dff); }
.muse-pill.is-amber { color: var(--dsw-alias-state-warn-label, #d90); }
.muse-pill.is-green { color: var(--dsw-alias-state-success-primary, #5cb85c); }
.muse-pill.is-red { color: var(--dsw-alias-state-error-primary, #f66); }
.muse-pill.is-red b, .muse-pill.is-green b, .muse-pill.is-blue b, .muse-pill.is-amber b { color: var(--dsw-alias-label-primary, #eee); }
/* \u91CC\u7A0B\u7891\u8F68\u9053\uFF08\u6280\u672F\u533A\u5185\uFF09 */
.muse-track { position: relative; display: flex; justify-content: space-between; margin: 6px 10px 2px; }
.muse-track::before { content: ""; position: absolute; top: 13px; left: 24px; right: 24px; height: 3px; border-radius: 2px; background: var(--dsw-alias-bg-layer-2, #2c2c2c); }
.muse-track .muse-fill { position: absolute; top: 13px; left: 24px; height: 3px; border-radius: 2px; background: var(--dsw-alias-state-success-primary, #5cb85c); transition: width .5s ease; max-width: calc(100% - 48px); }
.muse-track.is-warn .muse-fill { background: var(--dsw-alias-state-warn-label, #d90); }
.muse-track.is-fail .muse-fill { background: var(--dsw-alias-state-error-primary, #f66); }
.muse-mile { position: relative; z-index: 1; display: flex; flex-direction: column; align-items: center; gap: 6px; width: 72px; }
.muse-mile .muse-dot { width: 27px; height: 27px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-size: 13px; background: var(--dsw-alias-bg-layer-2, #2c2c2c); border: 2px solid transparent; color: var(--dsw-alias-label-dimmed, #666); }
.muse-mile.is-reached .muse-dot { background: color-mix(in srgb, var(--dsw-alias-state-success-primary, #5cb85c) 22%, var(--dsw-alias-bg-layer-2, #222)); color: var(--dsw-alias-state-success-primary, #5cb85c); }
.muse-mile.is-current .muse-dot { background: color-mix(in srgb, var(--dsw-alias-state-business-primary, #4a7dff) 26%, var(--dsw-alias-bg-layer-2, #222)); border-color: var(--dsw-alias-state-business-primary, #4a7dff); animation: muse-pulse 1.8s ease infinite; color: var(--dsw-alias-state-business-primary, #4a7dff); }
.muse-track.is-warn .muse-mile.is-current .muse-dot { border-color: var(--dsw-alias-state-warn-label, #d90); background: color-mix(in srgb, var(--dsw-alias-state-warn-label, #d90) 26%, var(--dsw-alias-bg-layer-2, #222)); color: var(--dsw-alias-state-warn-label, #d90); }
.muse-track.is-fail .muse-mile.is-current .muse-dot { border-color: var(--dsw-alias-state-error-primary, #f66); background: color-mix(in srgb, var(--dsw-alias-state-error-primary, #f66) 26%, var(--dsw-alias-bg-layer-2, #222)); color: var(--dsw-alias-state-error-primary, #f66); animation: none; }
.muse-mile span { font-size: 11px; color: var(--dsw-alias-label-tertiary, #8f8f8f); }
.muse-mile.is-reached span, .muse-mile.is-current span { color: var(--dsw-alias-label-primary, #eee); font-weight: 600; }
/* \u9884\u7B97\u4EEA\u8868 */
.muse-budget { display: flex; align-items: center; gap: 18px; flex-wrap: wrap; }
.muse-gauge { display: flex; align-items: center; gap: 9px; }
.muse-gauge svg { display: block; }
.muse-gauge .muse-gauge-text { display: flex; flex-direction: column; gap: 1px; }
.muse-gauge .muse-gauge-text b { font-size: 12px; font-variant-numeric: tabular-nums; }
.muse-gauge .muse-gauge-text span { font-size: 10.5px; color: var(--dsw-alias-label-dimmed, #888); }
.muse-gauge.is-warn circle.val { stroke: var(--dsw-alias-state-warn-label, #d90); }
.muse-gauge.is-over circle.val { stroke: var(--dsw-alias-state-error-primary, #f66); }
/* \u7F51\u683C */
.muse-grid { display: grid; grid-template-columns: 1.15fr 1fr; gap: 12px; }
@media (max-width: 900px) { .muse-grid { grid-template-columns: 1fr; } }
/* \u6D41\u6C34\u7EBF */
.muse-lines { display: flex; flex-direction: column; gap: 7px; }
.muse-eff { display: flex; align-items: center; gap: 9px; padding: 6px 8px; border-radius: 9px; background: var(--dsw-alias-bg-layer-1, #1d1d1d); }
details.muse-tech .muse-eff, details.muse-tech .muse-evi { background: var(--dsw-alias-bg-layer-1, #1d1d1d); }
.muse-eff.is-denied { background: color-mix(in srgb, var(--dsw-alias-state-error-primary, #f66) 10%, var(--dsw-alias-bg-layer-1, #1d1d1d)); }
.muse-eff .muse-ico { width: 26px; height: 26px; border-radius: 8px; flex: none; display: flex; align-items: center; justify-content: center; font-size: 13px; background: color-mix(in srgb, var(--dsw-alias-state-business-primary, #4a7dff) 15%, transparent); }
.muse-eff .muse-eff-main { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 3px; }
.muse-eff .muse-eff-path { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: 11.5px; }
.muse-eff .muse-eff-sub { display: flex; gap: 6px; align-items: center; font-size: 10px; color: var(--dsw-alias-label-dimmed, #777); }
.muse-eff .muse-eff-sub .muse-origin { border: 1px solid var(--dsw-alias-border-l2, #363636); border-radius: 6px; padding: 0 5px; }
.muse-stations { position: relative; display: flex; gap: 10px; align-items: center; flex: none; }
.muse-stations i { width: 9px; height: 9px; border-radius: 50%; background: var(--dsw-alias-bg-layer-2, #3a3a3a); border: 1px solid var(--dsw-alias-border-l2, #444); }
.muse-stations i.on-amber { background: var(--dsw-alias-state-warn-label, #d90); border-color: transparent; }
.muse-stations i.on-green { background: var(--dsw-alias-state-success-primary, #5cb85c); border-color: transparent; }
.muse-stations i.on-blue { background: var(--dsw-alias-state-business-primary, #4a7dff); border-color: transparent; animation: muse-breathe 1.4s ease infinite; }
.muse-stations i.on-red { background: var(--dsw-alias-state-error-primary, #f66); border-color: transparent; }
/* \u8BC1\u636E\u5899 */
.muse-evi { display: flex; gap: 9px; align-items: flex-start; padding: 7px 9px; border-radius: 9px; background: var(--dsw-alias-bg-layer-1, #1d1d1d); }
.muse-evi .muse-ico { width: 26px; height: 26px; border-radius: 50%; flex: none; display: flex; align-items: center; justify-content: center; font-size: 12px; }
.muse-evi.is-trusted .muse-ico { background: color-mix(in srgb, var(--dsw-alias-state-success-primary, #5cb85c) 16%, transparent); }
.muse-evi.is-untrusted .muse-ico { background: color-mix(in srgb, var(--dsw-alias-state-warn-label, #d90) 16%, transparent); }
.muse-evi .muse-evi-main { flex: 1; min-width: 0; display: flex; flex-direction: column; gap: 3px; }
.muse-evi .muse-evi-claim { line-height: 1.45; font-size: 11.5px; overflow: hidden; display: -webkit-box; -webkit-line-clamp: 2; -webkit-box-orient: vertical; }
.muse-evi .muse-evi-sub { display: flex; gap: 6px; align-items: center; font-size: 10px; color: var(--dsw-alias-label-dimmed, #777); }
.muse-tag { border-radius: 6px; padding: 0 5px; font-size: 10px; line-height: 16px; }
.muse-tag.is-green { color: var(--dsw-alias-state-success-primary, #5cb85c); background: color-mix(in srgb, var(--dsw-alias-state-success-primary, #5cb85c) 13%, transparent); }
.muse-tag.is-amber { color: var(--dsw-alias-state-warn-label, #d90); background: color-mix(in srgb, var(--dsw-alias-state-warn-label, #d90) 13%, transparent); }
.muse-tag.is-red { color: var(--dsw-alias-state-error-primary, #f66); background: color-mix(in srgb, var(--dsw-alias-state-error-primary, #f66) 13%, transparent); }
.muse-tag.is-blue { color: var(--dsw-alias-state-business-primary, #4a7dff); background: color-mix(in srgb, var(--dsw-alias-state-business-primary, #4a7dff) 13%, transparent); }
.muse-tag.is-dim { color: var(--dsw-alias-label-dimmed, #888); background: var(--dsw-alias-bg-layer-2, #2a2a2a); }
.muse-hash { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: 9.5px; color: var(--dsw-alias-label-dimmed, #666); }
.muse-note { color: var(--dsw-alias-label-dimmed, #888); font-size: 11.5px; line-height: 1.5; margin: 0; }
/* \u8BC4\u6D4B\u74E6\u7247 */
.muse-eval { display: flex; gap: 8px; flex-wrap: wrap; }
.muse-tile { display: flex; flex-direction: column; gap: 1px; padding: 5px 11px; border-radius: 8px; background: var(--dsw-alias-bg-layer-1, #1d1d1d); }
.muse-tile b { font-size: 13px; font-variant-numeric: tabular-nums; }
.muse-tile span { font-size: 10px; color: var(--dsw-alias-label-dimmed, #888); }
/* \u52A8\u6001 feed */
.muse-feed .muse-lines { max-height: 220px; overflow-y: auto; gap: 5px; }
.muse-feed-row { display: flex; gap: 9px; align-items: center; min-width: 0; }
.muse-feed-row .muse-ico { width: 22px; height: 22px; border-radius: 50%; flex: none; display: flex; align-items: center; justify-content: center; font-size: 10.5px; }
.muse-feed-row.is-muse .muse-ico { background: color-mix(in srgb, var(--dsw-alias-state-business-primary, #4a7dff) 17%, transparent); }
.muse-feed-row.is-write .muse-ico { background: color-mix(in srgb, var(--dsw-alias-state-warn-label, #d90) 17%, transparent); }
.muse-feed-row .muse-feed-label { flex: 1; min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; font-size: 11.5px; color: var(--dsw-alias-label-secondary, #bbb); }
.muse-feed-row.is-denied .muse-feed-label { color: var(--dsw-alias-state-error-primary, #f66); }
.muse-feed-row .muse-loc { flex: none; font-size: 9.5px; color: var(--dsw-alias-label-dimmed, #5f5f5f); font-variant-numeric: tabular-nums; }
/* \u7A7A\u6001 */
.muse-empty { margin: auto; max-width: 430px; text-align: center; color: var(--dsw-alias-label-tertiary, #999); display: flex; flex-direction: column; gap: 10px; align-items: center; }
.muse-empty h3 { margin: 0; font-size: 13.5px; font-weight: 600; color: var(--dsw-alias-label-secondary, #bbb); }
.muse-empty p { margin: 0; line-height: 1.65; }
.muse-orbit { position: relative; width: 84px; height: 84px; }
.muse-orbit i { position: absolute; border-radius: 50%; border: 1.5px dashed var(--dsw-alias-border-l2, #3a3a3a); animation: muse-spin 14s linear infinite; }
.muse-orbit i:nth-child(1) { inset: 0; }
.muse-orbit i:nth-child(2) { inset: 12px; animation-duration: 9s; animation-direction: reverse; }
.muse-orbit i:nth-child(3) { inset: 24px; animation-duration: 6s; }
.muse-orbit b { position: absolute; inset: 33px; border-radius: 50%; background: color-mix(in srgb, var(--dsw-alias-state-business-primary, #4a7dff) 25%, transparent); animation: muse-breathe 2.4s ease infinite; }
@keyframes muse-spin { to { transform: rotate(360deg); } }
`;
function ensureStyles() {
  if (typeof document === "undefined") return;
  if (document.getElementById(STYLE_ID) !== null) return;
  const tag = document.createElement("style");
  tag.id = STYLE_ID;
  tag.dataset.plugin = "dsh-muse-ui";
  tag.textContent = CSS;
  document.head.appendChild(tag);
}
var STEP_ICON = { pending: "\xB7", in_progress: "\u25D0", done: "\u2713", failed: "\u2715", skipped: "\u21B7" };
var ACTION_ICON = { "fs.write": "\u270F\uFE0F", "fs.edit": "\u{1F4DD}", "shell.exec": "\u26A1" };
function journey(status, hasVerification) {
  switch (status) {
    case "draft":
      return { reach: 0, current: 0, tone: "ok" };
    case "active":
      return { reach: 1, current: 1, tone: "ok" };
    case "waiting_approval":
    case "blocked":
      return { reach: 1, current: 1, tone: "warn" };
    case "done":
      return { reach: 3, current: null, tone: "ok" };
    case "failed":
    case "cancelled":
      return { reach: hasVerification ? 2 : 1, current: hasVerification ? 2 : 1, tone: "fail" };
    default:
      return { reach: 0, current: 0, tone: "ok" };
  }
}
function statusTone(status) {
  switch (status) {
    case "active":
      return "is-blue";
    case "done":
      return "is-green";
    case "waiting_approval":
    case "blocked":
      return "is-amber";
    case "failed":
    case "cancelled":
      return "is-red";
    default:
      return "is-dim";
  }
}
function stations(status) {
  switch (status) {
    case "proposed":
      return ["amber", "", ""];
    case "approved":
      return ["amber", "amber", ""];
    case "executing":
      return ["amber", "amber", "blue"];
    case "executed":
      return ["green", "green", "green"];
    case "failed":
      return ["amber", "amber", "red"];
    case "denied":
      return ["amber", "amber", "red"];
    case "rolled_back":
      return ["dim", "dim", "dim"];
    default:
      return ["", "", ""];
  }
}
function formatTokens(value) {
  if (typeof value !== "number" || !Number.isFinite(value)) return "\u2014";
  if (value >= 1e6) return `${(value / 1e6).toFixed(1)}M`;
  if (value >= 1e3) return `${(value / 1e3).toFixed(1)}k`;
  return String(value);
}
function shortPath(path) {
  const text = String(path ?? "");
  return text.length <= 34 ? text : `\u2026${text.slice(-33)}`;
}
function tx(t, key, fallback) {
  const value = t(key);
  return value === void 0 || value === null || value === key ? fallback : value;
}
function HeroCard({ unit, t }) {
  if (unit == null) {
    return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("section", { className: "muse-hero", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "muse-hero-top", children: /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-status is-dim", children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("i", { className: "muse-status-dot" }),
        t("hero.status.none")
      ] }) }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "muse-note", children: t("journey.none") })
    ] });
  }
  const status = unit.status ?? "draft";
  const tone = statusTone(status);
  const steps = unit.steps ?? [];
  const done = steps.filter((s) => s.status === "done").length;
  const trip = journey(status, unit.verification != null);
  const pct = steps.length > 0 ? Math.round(done / steps.length * 100) : status === "done" ? 100 : Math.round(trip.reach / 3 * 100);
  const progressTone = trip.tone === "fail" ? "is-fail" : trip.tone === "warn" ? "is-warn" : status === "done" ? "is-done" : "";
  const alertKey = trip.tone === "warn" ? `journey.alert.${status}` : trip.tone === "fail" ? `journey.${status}` : null;
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("section", { className: "muse-hero", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "muse-hero-top", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: `muse-status ${tone}`, children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("i", { className: "muse-status-dot" }),
        tx(t, `hero.status.${status}`, status)
      ] }),
      (unit.constraints?.length ?? 0) > 0 && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-note", title: unit.constraints.join("\n"), children: [
        "\u{1F4CE} ",
        t("journey.constraints"),
        " \xD7 ",
        unit.constraints.length
      ] })
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "muse-hero-objective", title: unit.objective, children: unit.objective ?? "\u2014" }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `muse-progress${progressTone ? ` ${progressTone}` : ""}`, children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "muse-progress-track", children: /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "muse-progress-fill", style: { width: `${pct}%` } }) }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-progress-label", children: steps.length > 0 ? t("hero.progress", { done, total: steps.length, pct }) : `${pct}%` })
    ] }),
    alertKey != null && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `muse-alert is-${trip.tone === "warn" ? "warn" : "fail"}`, children: [
      trip.tone === "warn" ? "\u23F3" : "\u26D4",
      " ",
      t(alertKey)
    ] }),
    steps.length > 0 && /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "muse-steplist", children: steps.map((step, index) => /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `muse-steprow is-${step.status}`, title: step.note ?? void 0, children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("i", { className: "muse-stepicon", children: step.status === "pending" ? index + 1 : STEP_ICON[step.status] ?? "\xB7" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-steptitle", children: step.title })
    ] }, step.id ?? index)) })
  ] });
}
function ArtifactsCard({ unit, t }) {
  const verified = unit?.verification != null;
  const artifacts = unit?.artifacts ?? [];
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("section", { className: "muse-card", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "muse-deliver-head", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("h4", { children: [
        "\u{1F4E6} ",
        t("delivery.artifacts")
      ] }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: `muse-seal ${verified ? "is-ok" : "is-wait"}`, children: verified ? `\u2713 ${t("delivery.verified")}` : `\u2026 ${t("delivery.unverified")}` })
    ] }),
    artifacts.length === 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "muse-note", children: t("artifacts.empty") }) : /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "muse-artifacts", children: artifacts.map((artifact) => /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-artifact", title: artifact.path, children: [
      "\u{1F4C4} ",
      shortPath(artifact.path),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: verified ? "muse-art-check" : "muse-art-pending", children: verified ? "\u2713" : "\u2026" })
    ] }, artifact.id ?? artifact.path)) })
  ] });
}
function LatestRow({ activity, t }) {
  const latest = activity.length > 0 ? activity[activity.length - 1] : null;
  if (latest == null) return null;
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `muse-latest is-${latest.kind}${latest.status === "denied" ? " is-denied" : ""}`, children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-latest-ico", children: latest.kind === "muse" ? "\u25CE" : "\u270E" }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-latest-k", children: t("latest.prefix") }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-latest-label", children: latest.label })
  ] });
}
function StatPills({ muse, t }) {
  const stats = muse.stats ?? {};
  const pills = [
    { icon: "\u25CE", tone: "is-blue", value: stats.museCalls ?? 0, label: t("stats.museCalls") },
    { icon: "\u270E", tone: "is-amber", value: stats.writeOps ?? 0, label: t("stats.writeOps") },
    { icon: "\u2713", tone: "is-green", value: stats.executed ?? 0, label: t("stats.executed") },
    { icon: "\u{1F6E1}", tone: "is-red", value: stats.denied ?? 0, label: t("stats.denied") },
    { icon: "\u2715", tone: "is-red", value: stats.failed ?? 0, label: t("stats.failed") }
  ];
  return /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "muse-pills", children: pills.map((pill) => /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: `muse-pill ${pill.tone}`, children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-ico", children: pill.icon }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("b", { children: pill.value }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: pill.label })
  ] }, pill.label)) });
}
function Gauge({ ratio, tone, value, label }) {
  const clamped = Math.max(0, Math.min(1, ratio || 0));
  const circumference = 2 * Math.PI * 15;
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `muse-gauge${tone ? ` ${tone}` : ""}`, children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("svg", { width: "36", height: "36", viewBox: "0 0 36 36", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("circle", { cx: "18", cy: "18", r: "15", fill: "none", stroke: "var(--dsw-alias-bg-layer-2, #2c2c2c)", strokeWidth: "4" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        "circle",
        {
          className: "val",
          cx: "18",
          cy: "18",
          r: "15",
          fill: "none",
          stroke: "var(--dsw-alias-state-business-primary, #4a7dff)",
          strokeWidth: "4",
          strokeLinecap: "round",
          strokeDasharray: `${clamped * circumference} ${circumference}`,
          transform: "rotate(-90 18 18)"
        }
      )
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-gauge-text", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("b", { children: value }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: label })
    ] })
  ] });
}
function JourneyTechCard({ unit, t }) {
  if (unit == null) return null;
  const trip = journey(unit.status, unit.verification != null);
  const milestones = ["draft", "active", "verify", "done"];
  const fillPercent = trip.current === null ? 100 : trip.current / (milestones.length - 1) * 100;
  const budget = unit.budget ?? {};
  const tokenRatio = budget.maxTokens ? (budget.spentTokens ?? 0) / budget.maxTokens : 0;
  const failureRatio = budget.maxFailures ? (budget.failures ?? 0) / budget.maxFailures : 0;
  const roundRatio = budget.maxRounds ? (budget.roundsUsed ?? 0) / budget.maxRounds : 0;
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("section", { className: "muse-card", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("h4", { children: [
      "\u{1F9ED} ",
      t("journey.title"),
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-count", children: [
        "v",
        unit.planVersion ?? 0
      ] })
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `muse-track${trip.tone === "ok" ? "" : ` is-${trip.tone}`}`, children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "muse-fill", style: { width: `calc(${fillPercent}% )` } }),
      milestones.map((key, index) => {
        const reached = index < trip.reach || trip.current === null && index <= trip.reach;
        const isCurrent = index === trip.current;
        return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `muse-mile${reached ? " is-reached" : ""}${isCurrent ? " is-current" : ""}`, children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "muse-dot", children: reached && !isCurrent ? "\u2713" : isCurrent ? trip.tone === "fail" ? "\u2715" : "\u25D0" : index + 1 }),
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: t(`milestone.${key}`) })
        ] }, key);
      })
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "muse-budget", style: { marginTop: 12 }, children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        Gauge,
        {
          ratio: tokenRatio,
          tone: tokenRatio > 0.9 ? "is-over" : tokenRatio > 0.7 ? "is-warn" : "",
          value: `${formatTokens(budget.spentTokens)}/${formatTokens(budget.maxTokens)}`,
          label: t("journey.budget.tokens")
        }
      ),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        Gauge,
        {
          ratio: failureRatio,
          tone: failureRatio >= 1 ? "is-over" : failureRatio >= 0.5 ? "is-warn" : "",
          value: `${budget.failures ?? 0}${budget.maxFailures != null ? `/${budget.maxFailures}` : ""}`,
          label: t("journey.budget.failures")
        }
      ),
      budget.maxRounds != null && /* @__PURE__ */ (0, import_jsx_runtime.jsx)(
        Gauge,
        {
          ratio: roundRatio,
          tone: roundRatio >= 1 ? "is-over" : roundRatio >= 0.7 ? "is-warn" : "",
          value: `${budget.roundsUsed ?? 0}/${budget.maxRounds}`,
          label: t("journey.budget.rounds")
        }
      )
    ] })
  ] });
}
function EffectRow({ effect, t }) {
  const fill = stations(effect.status);
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `muse-eff${effect.status === "denied" ? " is-denied" : ""}`, title: `${effect.action} ${effect.resource}${effect.note ? `
${effect.note}` : ""}`, children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-ico", children: ACTION_ICON[effect.action] ?? "\u{1F527}" }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-eff-main", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-eff-path", children: shortPath(effect.resource) }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-eff-sub", children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-origin", children: effect.origin === "auto" ? `\u{1F6E1} ${t("effect.origin.auto")}` : `\u{1F4D2} ${t("effect.origin.explicit")}` }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: tx(t, `effect.action.${effect.action}`, effect.action) })
      ] })
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-stations", title: t(`effect.status.${effect.status}`), children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("i", { className: fill[0] ? `on-${fill[0]}` : "" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("i", { className: fill[1] ? `on-${fill[1]}` : "" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("i", { className: fill[2] ? `on-${fill[2]}` : "" })
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: `muse-tag ${effect.status === "denied" ? "is-red" : effect.status === "executed" ? "is-green" : effect.status === "executing" ? "is-blue" : effect.status === "failed" ? "is-red" : effect.status === "rolled_back" ? "is-dim" : "is-amber"}`, children: [
      effect.status === "denied" ? "\u26D4 " : "",
      t(`effect.status.${effect.status}`)
    ] })
  ] });
}
function PipelineCard({ effects, t }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("section", { className: "muse-card", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("h4", { children: [
      "\u{1F6E1} ",
      t("pipeline.title"),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-count", children: effects.length })
    ] }),
    effects.length === 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "muse-note", children: t("pipeline.none") }) : /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "muse-lines", children: effects.map((effect) => /* @__PURE__ */ (0, import_jsx_runtime.jsx)(EffectRow, { effect, t }, effect.key)) })
  ] });
}
function EvidenceWall({ evidence, t, now }) {
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("section", { className: "muse-card", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("h4", { children: [
      "\u{1F4CE} ",
      t("evidence.title"),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-count", children: evidence.length })
    ] }),
    evidence.length === 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "muse-note", children: t("evidence.none") }) : /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "muse-lines", children: evidence.map((item) => {
      const stale = item.freshUntil != null && item.freshUntil < now;
      return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `muse-evi is-${item.trust === "trusted" ? "trusted" : "untrusted"}`, children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-ico", children: item.trust === "trusted" ? "\u{1F6E1}" : "\u26A0\uFE0F" }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-evi-main", children: [
          /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-evi-claim", children: item.claim }),
          /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-evi-sub", children: [
            /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: `muse-tag is-${item.trust === "trusted" ? "green" : "amber"}`, children: t(`trust.${item.trust}`) }),
            item.hash != null && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-hash", children: [
              "#",
              item.hash
            ] }),
            item.freshUntil != null && /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: `muse-tag ${stale ? "is-red" : "is-green"}`, children: [
              stale ? "\u231B" : "\u{1F552}",
              " ",
              stale ? t("fresh.stale") : t("fresh.ok")
            ] })
          ] })
        ] })
      ] }, item.id);
    }) })
  ] });
}
function EvalCard({ evaluation, t }) {
  const summary = evaluation?.summary;
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("section", { className: "muse-card", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("h4", { children: [
      "\u{1F4CA} ",
      t("eval.title")
    ] }),
    summary != null ? /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "muse-eval", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-tile", children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("b", { children: [
          (100 * (summary.verifiedSuccessRate ?? 0)).toFixed(0),
          "%"
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: t("delivery.eval.verified") })
      ] }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-tile", children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("b", { children: [
          (100 * (summary.duplicateSideEffectRate ?? 0)).toFixed(1),
          "%"
        ] }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: t("delivery.eval.duplicates") })
      ] }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-tile", children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("b", { children: formatTokens(summary.totalTokens) }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { children: t("delivery.eval.tokens") })
      ] })
    ] }) : /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "muse-note", children: t("delivery.noEval") })
  ] });
}
function Feed({ activity, t }) {
  const newestFirst = [...activity].reverse();
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("section", { className: "muse-card muse-feed", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("h4", { children: [
      "\u{1F4E1} ",
      t("feed.title"),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-count", children: activity.length })
    ] }),
    newestFirst.length === 0 ? /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { className: "muse-note", children: t("feed.empty") }) : /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "muse-lines", children: newestFirst.map((row) => /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: `muse-feed-row is-${row.kind}${row.status === "denied" ? " is-denied" : ""}`, children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-ico", children: row.kind === "muse" ? "\u25CE" : "\u270E" }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("span", { className: "muse-feed-label", children: row.label }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: `muse-tag ${row.status === "running" ? "is-blue" : row.status === "ok" ? "is-green" : "is-red"}`, children: [
        row.status === "running" ? "\u25D0" : row.status === "ok" ? "\u2713" : row.status === "denied" ? "\u26D4" : "\u2715",
        " ",
        t(`feed.status.${row.status}`)
      ] }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("span", { className: "muse-loc", children: [
        "T",
        row.turn
      ] })
    ] }, row.seq)) })
  ] });
}
function TechDetails({ muse, t, now }) {
  const unit = muse.workunit ?? null;
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("details", { className: "muse-tech", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("summary", { children: [
      "\u{1F527} ",
      t("tech.toggle")
    ] }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "muse-tech-body", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(StatPills, { muse, t }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(JourneyTechCard, { unit, t }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "muse-grid", children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)(PipelineCard, { effects: muse.effects ?? [], t }),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)(EvidenceWall, { evidence: muse.evidence ?? [], t, now })
      ] }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(EvalCard, { evaluation: muse.eval, t }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)(Feed, { activity: muse.activity ?? [], t })
    ] })
  ] });
}
function MuseView({ useProjection, t }) {
  const muse = useProjection?.("muse");
  const [now, setNow] = (0, import_react.useState)(() => Date.now());
  (0, import_react.useEffect)(() => {
    const timer = setInterval(() => setNow(Date.now()), 3e4);
    return () => clearInterval(timer);
  }, []);
  if (muse == null || (muse.seq ?? 0) === 0) {
    return /* @__PURE__ */ (0, import_jsx_runtime.jsx)("div", { className: "muse-view", children: /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "muse-empty", children: [
      /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "muse-orbit", children: [
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("i", {}),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("i", {}),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("i", {}),
        /* @__PURE__ */ (0, import_jsx_runtime.jsx)("b", {})
      ] }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("h3", { children: t("empty.title") }),
      /* @__PURE__ */ (0, import_jsx_runtime.jsx)("p", { children: t("empty.body") })
    ] }) });
  }
  return /* @__PURE__ */ (0, import_jsx_runtime.jsxs)("div", { className: "muse-view", children: [
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(HeroCard, { unit: muse.workunit, t }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(ArtifactsCard, { unit: muse.workunit, t }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(LatestRow, { activity: muse.activity ?? [], t }),
    /* @__PURE__ */ (0, import_jsx_runtime.jsx)(TechDetails, { muse, t, now })
  ] });
}
function apply(ctx) {
  ensureStyles();
  ctx.effect(() => ctx.locale.register(NS, { zh, en }), "dsh-muse-ui: dictionaries");
  const t = ctx.locale.bind(NS);
  ctx.slots.inject("conversation.view", () => ctx.slots.register({
    name: "conversation.view",
    id: "muse",
    order: 20,
    locale: NS,
    label: () => t("view.muse"),
    inject: () => ({})
  }, MuseView));
}

		return module.exports;
	}
});
